### ISSUE TITLE
Backend routes

### ISSUE THREAD

**Issue by linakherchi** [lee-joseph-i/supersana#3]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Member routes do not need to be nested. If you open the link related to `superfluous routes`, you will have the necessary info on which routes need to be nested.

**Comment by lee-joseph-i** [comment]
Looking into this.
