### ISSUE TITLE
Frontend routes

### ISSUE THREAD

**Issue by linakherchi** [lee-joseph-i/supersana#4]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
1. What is the difference between `TasksDueToday` and `TasksToday`? 
2. I see that you have a lot of repetitive presentational components depending on which route the user will be visiting. If you haven't think about it, you can map different ways in which you can make your code drier (i.e. using one container to wrap numerous presentational components, be attentive on not lifting up your state)
3. Are you referring to projects when you write sections ?(i.e SectionsForm, SectionsIndex)

**Comment by lee-joseph-i** [comment]
1. `TasksDueToday` and `TasksToday` are the same, I'll correct that now. 
2. Good point, I need to look into this some more to understand it properly.
3. Sections are something like "tables" that you can use in Asana to categorize your tasks that are in a project. You can create and "drag" sections where you want them to go. See the screenshot below.
![Screen Shot 2020-01-06 at 3 29 10 PM](https://user-images.githubusercontent.com/39147326/71856648-76d4ab80-3099-11ea-978b-78d89612c305.png)
